name: BoomNode Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    name: Build All Platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # 64-битные
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
            ext: .exe
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          # 32-битные
          - goos: linux
            goarch: 386
          - goos: windows
            goarch: 386
            ext: .exe

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Tidy modules
        run: go mod tidy

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ github.ref_name }}
        run: |
          VERSION_CLEAN=${VERSION#v}
          go build -ldflags "-X main.Version=${VERSION_CLEAN} -X github.com/BSXLAbS2025/boomnode/internal/boomex.Version=${VERSION_CLEAN}" -o boomnode-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} ./cmd/boomnode

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: boomnode-${{ matrix.goos }}-${{ matrix.goarch }}
          path: boomnode-*
