name: Build and Release BoomNode

on:
  push:
    tags:
      - 'v*' # Запускать при создании тега вроде v0.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
            ext: .exe
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o boomnode-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} ./cmd/boomnode

      - name: Upload Artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          files: boomnode-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
